# Site settings
title: Avoiding Exposition
email: k.garza@manchester.ac.uk
description: > # this means to ignore newlines until "baseurl:"
 I'm a PhD Candidate in the School of Computer Science at Univeristy of Manchester. I study sciensits behaviour towards Data Sharing and Collaboration.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kjgarza.github.io" # the base hostname & protocol for your site
twitter_username: kriztean
github_username:  kjgarza
linkedin_username:  "https://uk.linkedin.com/in/kjgarza"

profile_picture: https://media.licdn.com/mpr/mpr/shrinknp_200_200/AAEAAQAAAAAAAAPaAAAAJGE0ZTY1ZGE3LWZkYWQtNDAzZi1hYjU3LTk4MjRmOGRlYzYzNg.jpg

# Build settings
markdown: kramdown
