title: Kristian Garza - Perosnal page
author:  Kristian Garza
email: kj.garza@gmail.com
description: >-
  High-performing Product Designer with a passion for the Open Science community with seven years of experience impacting positive organizational outcomes through detailed UX research and sound architecture design.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://kjgarza.github.io/"

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

plugins:
  - jekyll-feed
  - jekyll-menus

