# Site settings
title: For Example In ...
email: k.garza@manchester.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Kristian Garza comments and opinions.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kjgarza.github.io" # the base hostname & protocol for your site
twitter_username: kriztean
github_username:  kjgarza
linkedin_username:  "https://uk.linkedin.com/in/kjgarza"

# Build settings
markdown: kramdown
