module.exports = [
  {
    id: "knowledge-graph-engine",
    company: "Digital Science",
    title: "Knowledge Graph Engine - Company Knowledge as a Graph for AI Agents",
    description:
      "Architected a hexagonal Effect-TS pipeline that extracts a Postgres-backed knowledge graph from company documents and serves it to AI agents over MCP.",
    tags: ["Knowledge Graphs", "Effect-TS", "LLMs"],
    status: "published",
    image: "/assets/images/knowledge-graph-engine-hero.png",
    link: "/work/knowledge-graph-engine",
    featured: false,
    gridClass: "col-span-2 row-span-1",
  },
  {
    id: "repo-atlas-catalogue",
    company: "Digital Science",
    title: "Repo Atlas - Making 1,000+ Repos Discoverable with LLMs",
    description:
      "Built an LLM-powered catalogue that scans an entire GitHub org and answers \"does a repo already exist that does X?\" through an MCP server and web UI.",
    tags: ["LLMs", "MCP", "TypeScript"],
    status: "published",
    image: "/assets/images/repo-atlas-hero.png",
    link: "/work/repo-atlas-catalogue",
    featured: false,
    gridClass: "col-span-2 row-span-1",
  },
  {
    id: "query-translation-api",
    company: "Digital Science",
    title: "Query Translation API - Natural Language to Database Queries",
    description:
      "Architected and launched a FastAPI microservice that turns natural-language requests into optimized Dimensions searches.",
    tags: ["APIs", "LLMs", "Python"],
    status: "published",
    image: "/assets/images/nl2query-hero.png",
    link: "/work/query-translation-api",
    featured: true,
    gridClass: "col-span-2 row-span-1",
  },
  {
    id: "datacite-design-system",
    company: "DataCite",
    title: "Harmonizing with a Design System",
    description: "Crafted a Design System for all DataCite frontend services.",
    tags: ["Design systems", "UX Design"],
    status: "published",
    image: "/assets/images/design-system-hero.png",
    link: "/work/creating-a-design-system",
    featured: true,
    imageContainer: "h-full rounded-tl-2xl px-6 pt-6",
    gridClass: "col-span-1 row-span-2",
  },
  {
    id: "datacite-data-usage-processing",
    company: "DataCite",
    title: "Innovating Data Usage Processing Services",
    description:
      "Pioneering an alternative to existing data usage processing services through web tracker development.",
    tags: ["Product Design", "UX Research"],
    status: "published",
    image: "/assets/images/designsprint-eosc-Medium.png",
    link: "/work/innovating-data-usage-processing-services",
    featured: true,
    gridClass: "col-span-1 row-span-1",
  },
  {
    id: "datacite-usage-reports-api",
    company: "DataCite",
    title: "Usage Reports API - Research Data Metrics at Scale",
    description:
      "Designed and delivered Sashimi—a Rails API that ingests, validates, and stores large SUSHI usage reports at 50,000-dataset scale.",
    tags: ["Serverless", "Ruby on Rails"],
    status: "published",
    image: "/assets/images/mdc-hero.png",
    link: "/work/datacite-usage-reports-api",
    featured: true,
    gridClass: "col-span-1 row-span-1",
  },
  {
    id: "redesigning-datacite-harvesting-services",
    company: "DataCite",
    title: "Redesigning DataCite's Harvesting Services",
    description: "Redesigned DataCite's Harvesting Services from the ground up to boost service utilization and unlock new revenue opportunities.",
    tags: ["UX Research", "Service Design"],
    status: "published",
    image: "https://i.imgur.com/Y8Jn1lP.png",
    link: "/work/redesigning-datacite-harvesting-services",
    featured: true,
    gridClass: "col-span-2 row-span-1",
  },
];
